import StyledComponentsRegistry from "@/lib/registry";
import Nav from "./_components/Nav/Nav";
import { Metadata, Viewport } from "next";
import { ReactNode } from "react";
export const viewport: Viewport = {
  themeColor: "black",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  title: "News Scrap",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    icon: "/icon-192x192.png",
    shortcut: "/test_icon.png",
    apple: "/test_icon.png",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/test_icon.png",
    },
  },
};
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Nav />
          {children}
          {modal}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
