name: Sync main to main

on:
  push:
    branches: [main] # 원본 레포지토리의 main 브랜치가 업데이트될 때 실행

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      # 1. 원본 레포지토리의 main 브랜치 가져오기
      - name: Checkout upstream repository
        uses: actions/checkout@v3
        with:
          repository: ChipoChipo1/News_Frontend # 원본 레포지토리
          ref: main                            # 가져올 브랜치
          token: ${{ secrets.AUTH_TOKEN }}     # 원본 레포지토리 접근용 PAT

      # 2. Git 사용자 정보 설정
      - name: Configure Git User
        run: |
          git config --global user.name "vaynel"
          git config --global user.email "ss04041@gmail.com"

      # 3. 나의 개인 레포지토리의 main 브랜치로 Push
      - name: Push to my fork
        run: |
          git remote add myfork https://vaynel:${{ secrets.vercel_news_front_dev }}@github.com/vaynel/New_Front_Dev.git
          git push myfork main --force
