name: git push into another repo to deploy to vercel
on:
  push:
    branches: [master]

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      # 1. 원본 레포지토리 가져오기
      - name: Checkout upstream repository
        uses: actions/checkout@v3
        with:
          repository: ChipoChipo1/News_Frontend
          ref: master
          token: ${{ secrets.AUTH_TOKEN }}

      # 2. Git 설정 및 main 브랜치 생성
      - name: Configure Git User and Create main branch
        run: |
          git config --global user.name "vaynel"
          git config --global user.email "ss04041@gmail.com"
          git checkout -b main # master를 기반으로 main 브랜치 생성

      # 3. 나의 개인 레포지토리로 Push
      - name: Push changes to my fork
        run: |
          git remote add myfork https://vaynel:${{ secrets.AUTH_TOKEN }}@github.com/vaynel/New_Front_Dev.git
          git push myfork main --force
